# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(876, 809)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setEnabled(True)
        self.centralWidget.setObjectName("centralWidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralWidget)
        self.gridLayout_2.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_2.setSpacing(6)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.frame = QtWidgets.QFrame(self.centralWidget)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btn_connect = QtWidgets.QPushButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_connect.sizePolicy().hasHeightForWidth())
        self.btn_connect.setSizePolicy(sizePolicy)
        self.btn_connect.setObjectName("btn_connect")
        self.horizontalLayout.addWidget(self.btn_connect)
        self.label_device = QtWidgets.QLabel(self.frame)
        self.label_device.setObjectName("label_device")
        self.horizontalLayout.addWidget(self.label_device)
        self.comboBox = QtWidgets.QComboBox(self.frame)
        self.comboBox.setObjectName("comboBox")
        self.horizontalLayout.addWidget(self.comboBox)
        self.btn_goahead = QtWidgets.QPushButton(self.frame)
        self.btn_goahead.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_goahead.sizePolicy().hasHeightForWidth())
        self.btn_goahead.setSizePolicy(sizePolicy)
        self.btn_goahead.setObjectName("btn_goahead")
        self.horizontalLayout.addWidget(self.btn_goahead)
        self.gridLayout_2.addWidget(self.frame, 0, 0, 1, 1)
        self.tabWiget = QtWidgets.QTabWidget(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWiget.sizePolicy().hasHeightForWidth())
        self.tabWiget.setSizePolicy(sizePolicy)
        self.tabWiget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tabWiget.setAutoFillBackground(False)
        self.tabWiget.setObjectName("tabWiget")
        self.tab_list = QtWidgets.QWidget()
        self.tab_list.setObjectName("tab_list")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.tab_list)
        self.gridLayout_3.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_3.setSpacing(6)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.listWidget_classes = QtWidgets.QListWidget(self.tab_list)
        self.listWidget_classes.setEnabled(True)
        self.listWidget_classes.setObjectName("listWidget_classes")
        self.gridLayout_3.addWidget(self.listWidget_classes, 1, 1, 1, 1)
        self.listWidget_methods = QtWidgets.QListWidget(self.tab_list)
        self.listWidget_methods.setObjectName("listWidget_methods")
        self.gridLayout_3.addWidget(self.listWidget_methods, 1, 4, 1, 1)
        self.label_classes = QtWidgets.QLabel(self.tab_list)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_classes.setFont(font)
        self.label_classes.setAutoFillBackground(False)
        self.label_classes.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_classes.setAlignment(QtCore.Qt.AlignCenter)
        self.label_classes.setObjectName("label_classes")
        self.gridLayout_3.addWidget(self.label_classes, 0, 1, 1, 1)
        self.label_methods = QtWidgets.QLabel(self.tab_list)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_methods.setFont(font)
        self.label_methods.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_methods.setAlignment(QtCore.Qt.AlignCenter)
        self.label_methods.setObjectName("label_methods")
        self.gridLayout_3.addWidget(self.label_methods, 0, 4, 1, 1)
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setSpacing(6)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.btn_showMethods = QtWidgets.QPushButton(self.tab_list)
        self.btn_showMethods.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_showMethods.sizePolicy().hasHeightForWidth())
        self.btn_showMethods.setSizePolicy(sizePolicy)
        self.btn_showMethods.setObjectName("btn_showMethods")
        self.gridLayout_5.addWidget(self.btn_showMethods, 0, 0, 1, 1)
        self.btn_hook = QtWidgets.QPushButton(self.tab_list)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_hook.sizePolicy().hasHeightForWidth())
        self.btn_hook.setSizePolicy(sizePolicy)
        self.btn_hook.setObjectName("btn_hook")
        self.gridLayout_5.addWidget(self.btn_hook, 0, 1, 1, 1)
        self.btn_analyze = QtWidgets.QPushButton(self.tab_list)
        self.btn_analyze.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_analyze.sizePolicy().hasHeightForWidth())
        self.btn_analyze.setSizePolicy(sizePolicy)
        self.btn_analyze.setDefault(False)
        self.btn_analyze.setFlat(False)
        self.btn_analyze.setObjectName("btn_analyze")
        self.gridLayout_5.addWidget(self.btn_analyze, 0, 2, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_5, 2, 4, 2, 1)
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setSpacing(6)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.lineEdit_findclass = QtWidgets.QLineEdit(self.tab_list)
        self.lineEdit_findclass.setObjectName("lineEdit_findclass")
        self.gridLayout_4.addWidget(self.lineEdit_findclass, 0, 0, 1, 1)
        self.btn_find = QtWidgets.QPushButton(self.tab_list)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_find.sizePolicy().hasHeightForWidth())
        self.btn_find.setSizePolicy(sizePolicy)
        self.btn_find.setObjectName("btn_find")
        self.gridLayout_4.addWidget(self.btn_find, 0, 1, 1, 1)
        self.btn_refresh = QtWidgets.QPushButton(self.tab_list)
        self.btn_refresh.setObjectName("btn_refresh")
        self.gridLayout_4.addWidget(self.btn_refresh, 0, 2, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_4, 2, 1, 2, 1)
        self.tabWiget.addTab(self.tab_list, "")
        self.tab_hook = QtWidgets.QWidget()
        self.tab_hook.setObjectName("tab_hook")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.tab_hook)
        self.gridLayout_6.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_6.setSpacing(6)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.textEdit_javascript = QtWidgets.QTextEdit(self.tab_hook)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textEdit_javascript.sizePolicy().hasHeightForWidth())
        self.textEdit_javascript.setSizePolicy(sizePolicy)
        self.textEdit_javascript.setObjectName("textEdit_javascript")
        self.gridLayout_6.addWidget(self.textEdit_javascript, 0, 0, 1, 1)
        self.btn_loadscript = QtWidgets.QPushButton(self.tab_hook)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_loadscript.sizePolicy().hasHeightForWidth())
        self.btn_loadscript.setSizePolicy(sizePolicy)
        self.btn_loadscript.setObjectName("btn_loadscript")
        self.gridLayout_6.addWidget(self.btn_loadscript, 1, 0, 1, 1)
        self.textEdit_jsoutput = QtWidgets.QTextEdit(self.tab_hook)
        self.textEdit_jsoutput.setObjectName("textEdit_jsoutput")
        self.gridLayout_6.addWidget(self.textEdit_jsoutput, 2, 0, 1, 1)
        self.tabWiget.addTab(self.tab_hook, "")
        self.tab_memory = QtWidgets.QWidget()
        self.tab_memory.setObjectName("tab_memory")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.tab_memory)
        self.gridLayout_10.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_10.setSpacing(6)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSpacing(6)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSpacing(6)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_string = QtWidgets.QLabel(self.tab_memory)
        self.label_string.setObjectName("label_string")
        self.horizontalLayout_3.addWidget(self.label_string)
        self.lineEdit_string = QtWidgets.QLineEdit(self.tab_memory)
        self.lineEdit_string.setEnabled(True)
        self.lineEdit_string.setObjectName("lineEdit_string")
        self.horizontalLayout_3.addWidget(self.lineEdit_string)
        self.btn_hex = QtWidgets.QPushButton(self.tab_memory)
        self.btn_hex.setObjectName("btn_hex")
        self.horizontalLayout_3.addWidget(self.btn_hex)
        self.lineEdit_hex = QtWidgets.QLineEdit(self.tab_memory)
        self.lineEdit_hex.setObjectName("lineEdit_hex")
        self.horizontalLayout_3.addWidget(self.lineEdit_hex)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setSpacing(6)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setSpacing(6)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.checkBox_readable = QtWidgets.QCheckBox(self.tab_memory)
        self.checkBox_readable.setObjectName("checkBox_readable")
        self.horizontalLayout_4.addWidget(self.checkBox_readable)
        self.checkBox_writable = QtWidgets.QCheckBox(self.tab_memory)
        self.checkBox_writable.setObjectName("checkBox_writable")
        self.horizontalLayout_4.addWidget(self.checkBox_writable)
        self.btn_search = QtWidgets.QPushButton(self.tab_memory)
        self.btn_search.setEnabled(True)
        self.btn_search.setObjectName("btn_search")
        self.horizontalLayout_4.addWidget(self.btn_search)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.listWidget_address = QtWidgets.QListWidget(self.tab_memory)
        self.listWidget_address.setObjectName("listWidget_address")
        self.verticalLayout_3.addWidget(self.listWidget_address)
        self.horizontalLayout_2.addLayout(self.verticalLayout_3)
        self.line = QtWidgets.QFrame(self.tab_memory)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout_2.addWidget(self.line)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setSpacing(6)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setSpacing(6)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_address = QtWidgets.QLabel(self.tab_memory)
        self.label_address.setObjectName("label_address")
        self.horizontalLayout_5.addWidget(self.label_address)
        self.lineEdit_address = QtWidgets.QLineEdit(self.tab_memory)
        self.lineEdit_address.setObjectName("lineEdit_address")
        self.horizontalLayout_5.addWidget(self.lineEdit_address)
        self.btn_write = QtWidgets.QPushButton(self.tab_memory)
        self.btn_write.setObjectName("btn_write")
        self.horizontalLayout_5.addWidget(self.btn_write)
        self.verticalLayout_5.addLayout(self.horizontalLayout_5)
        self.listWidget_output = QtWidgets.QListWidget(self.tab_memory)
        self.listWidget_output.setObjectName("listWidget_output")
        self.verticalLayout_5.addWidget(self.listWidget_output)
        self.horizontalLayout_2.addLayout(self.verticalLayout_5)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.gridLayout_10.addLayout(self.verticalLayout_2, 1, 1, 1, 1)
        self.tabWiget.addTab(self.tab_memory, "")
        self.gridLayout_2.addWidget(self.tabWiget, 1, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 876, 22))
        self.menuBar.setObjectName("menuBar")
        self.menuMenu = QtWidgets.QMenu(self.menuBar)
        self.menuMenu.setObjectName("menuMenu")
        MainWindow.setMenuBar(self.menuBar)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.actionNew_Project = QtWidgets.QAction(MainWindow)
        self.actionNew_Project.setObjectName("actionNew_Project")
        self.actionSave_Project = QtWidgets.QAction(MainWindow)
        self.actionSave_Project.setObjectName("actionSave_Project")
        self.actionEdit_Project = QtWidgets.QAction(MainWindow)
        self.actionEdit_Project.setObjectName("actionEdit_Project")
        self.menuMenu.addAction(self.actionNew_Project)
        self.menuMenu.addAction(self.actionSave_Project)
        self.menuMenu.addAction(self.actionEdit_Project)
        self.menuBar.addAction(self.menuMenu.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWiget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Andromeda"))
        self.btn_connect.setText(_translate("MainWindow", "Connect"))
        self.label_device.setText(_translate("MainWindow", "No Device Connected"))
        self.btn_goahead.setText(_translate("MainWindow", "Attach"))
        self.label_classes.setText(_translate("MainWindow", "Classes"))
        self.label_methods.setText(_translate("MainWindow", "Methods"))
        self.btn_showMethods.setText(_translate("MainWindow", "Show Methods"))
        self.btn_hook.setText(_translate("MainWindow", "    Hook   "))
        self.btn_analyze.setText(_translate("MainWindow", "Analyze"))
        self.btn_find.setText(_translate("MainWindow", "Find"))
        self.btn_refresh.setText(_translate("MainWindow", "Refresh"))
        self.tabWiget.setTabText(self.tabWiget.indexOf(self.tab_list), _translate("MainWindow", "List"))
        self.btn_loadscript.setText(_translate("MainWindow", "Load Script"))
        self.tabWiget.setTabText(self.tabWiget.indexOf(self.tab_hook), _translate("MainWindow", "Hook"))
        self.label_string.setText(_translate("MainWindow", "String"))
        self.btn_hex.setText(_translate("MainWindow", "Hex >>"))
        self.checkBox_readable.setText(_translate("MainWindow", "Readable"))
        self.checkBox_writable.setText(_translate("MainWindow", "Writable"))
        self.btn_search.setText(_translate("MainWindow", "Search"))
        self.label_address.setText(_translate("MainWindow", "Address"))
        self.btn_write.setText(_translate("MainWindow", "Write"))
        self.tabWiget.setTabText(self.tabWiget.indexOf(self.tab_memory), _translate("MainWindow", "Memory"))
        self.menuMenu.setTitle(_translate("MainWindow", "Menu"))
        self.actionNew_Project.setText(_translate("MainWindow", "New Project"))
        self.actionSave_Project.setText(_translate("MainWindow", "Save Project"))
        self.actionEdit_Project.setText(_translate("MainWindow", "Edit Project"))

